TournamentMaker.Web/Models/View/StandingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace TournamentReport.Models
{
    public class StandingsViewModel
    {
        public string Title { get; set; }
        public IEnumerable<Team> Teams { get; set; }
        public IEnumerable<Round> Rounds { get; set; }

        public IEnumerable<IGrouping<string, Team>> Groups
        {
            get
            {
                if (Teams.Any(t => !String.IsNullOrEmpty(t.Group)))
                {
                    return Teams.GroupBy(t => t.Group);
                }
                return Enumerable.Empty<IGrouping<string, Team>>();
            }
        }
    }
}

TournamentMaker.Web/Controllers/HomeController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using TournamentReport.Models;

namespace TournamentReport.Controllers
{
    public class HomeController : Controller
    {
        readonly TournamentContext db = new TournamentContext();

        public ActionResult Index()
        {
            var tournaments = db.Tournaments.Include(t => t.Owner).ToList();
            return View(new TournamentListModel(tournaments));
        }

        public ActionResult Standings(string tournamentSlug)
        {
            var tournament = db.Tournaments
                .Include(t => t.Teams)
                .Include(t => t.Rounds.Select(r => r.Games.Select(g => g.Field)))
                .Include(t => t.Rounds)
                .First(t => t.Slug == tournamentSlug);

            var standings = tournament.Teams.ToList().OrderByDescending(t => t.Points)
                .ThenByDescending(t => t.GoalsScored - t.GoalsAgainst)
                .ThenBy(t => t.GoalsAgainst)
                .ThenBy(t => t.Id);

            // Temporary hack
            ViewBag.TournamentSlug = tournament.Slug;

            return View(new StandingsViewModel
            {
                Title = tournament.Name,
                Rounds = tournament.Rounds,
                Teams = standings,
            });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TournamentMaker.Web/Controllers/RoundsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using TournamentReport.Models;

namespace TournamentReport.Controllers
{
    public class RoundsController : Controller
    {
        readonly TournamentContext db = new TournamentContext();

        //
        // GET: /Rounds/

        public ViewResult Index()
        {
            var rounds = db.Rounds.Include(r => r.Tournament);
            return View(rounds.ToList());
        }

        //
        // GET: /Rounds/Details/5

        public ViewResult Details(int id)
        {
            Round round = db.Rounds.Find(id);
            return View(round);
        }

        //
        // GET: /Rounds/Create

        public ActionResult Create(string tournamentSlug)
        {
            var tournament = db.Tournaments.First(t => t.Slug == tournamentSlug);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "Id", "Name", tournament.Id);
            return View();
        }

        //
        // POST: /Rounds/Create

        [HttpPost]
        public ActionResult Create(Round round, string tournamentSlug)
        {
            if (ModelState.IsValid)
            {
                db.Rounds.Add(round);
                db.SaveChanges();
                return RedirectToAction("Standings", "Home", new {tournamentSlug});
            }

            ViewBag.TournamentId = new SelectList(db.Tournaments, "Id", "Name", round.TournamentId);
            return View(round);
        }

        //
        // GET: /Rounds/Edit/5

        public ActionResult Edit(int id)
        {
            Round round = db.Rounds.Find(id);
            ViewBag.TournamentId = new SelectList(db.Tournaments, "Id", "Name", round.TournamentId);
            return View(round);
        }

        //
        // POST: /Rounds/Edit/5

        [HttpPost]
        public ActionResult Edit(Round round, string tournamentSlug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(round).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Standings", "Home", new {tournamentSlug});
            }
            ViewBag.TournamentId = new SelectList(db.Tournaments, "Id", "Name", round.TournamentId);
            return View(round);
        }

        //
        // GET: /Rounds/Delete/5

        public ActionResult Delete(int id)
        {
            Round round = db.Rounds.Find(id);
            return View(round);
        }

        //
        // POST: /Rounds/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string tournamentSlug)
        {
            Round round = db.Rounds.Find(id);
            db.Rounds.Remove(round);
            db.SaveChanges();
            return RedirectToAction("Standings", "Home", new {tournamentSlug});
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TournamentMaker.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

TournamentMaker.Web/Views/Home/Index.cshtml
@model TournamentListModel

@{
    ViewBag.Title = "Tournaments";
}

<h2>Tournament List</h2>

<table>
    <tr valign="top">
        <th>Tournament</th>
        <th>Description</th>
        <th></th>
    </tr>
@foreach (var tournament in Model.RecentTournaments)
{
    <tr>
        <td>
            <a href="/tournaments/@tournament.Slug">@Html.DisplayFor(m => tournament.Name)</a>
        </td>
        <td>
            <strong>@Html.DisplayFor(m => tournament.Description)</strong>
        </td>
        <td>
        @if (ViewBag.CanEditTournament(tournament)) {
            @Html.ActionLink("Edit", "Edit", "Tournaments", new { id = tournament.Id, tournamentSlug = tournament.Slug }, null)
        }
        </td>
    </tr>
}
    <tr><td colspan="2" style="padding: 10px;">past years</td></tr>
@foreach (var tournament in Model.ArchivedTournaments)
{
    <tr>
        <td>
            <a href="/tournaments/@tournament.Slug">@Html.DisplayFor(m => tournament.Name)</a>
        </td>
        <td>
            @Html.DisplayFor(m => tournament.Description)
        </td>
        <td>
        @if (ViewBag.CanEditTournament(tournament)) {
            @Html.ActionLink("Edit", "Edit", "Tournaments", new { id = tournament.Id, tournamentSlug = tournament.Slug }, null)
        }
        </td>
    </tr>
}
</table>

@if (ViewBag.HasEditAccess) {
    <p>@Html.RouteLink("Create New", "CreateTournament", new { Action = "Create", Controller = "Tournaments" })</p>
}

TournamentMaker.Web/Views/Home/Standings.cshtml
@model StandingsViewModel

@{
    ViewBag.Title = "Standings";
}

<h2><em>Standings:</em> @Model.Title</h2>

<table>
    <tr valign="top">
        <td>
            <h2>Total Standings</h2>
            @Html.Partial("Teams", Model.Teams)
            
            @if (!Model.Groups.Any()) {
                <em>@Html.ActionLink("Add Team", "Create", "Teams", new {tournamentSlug = ViewBag.TournamentSlug}, null)</em>
            }

            @foreach (var grouping in Model.Groups) {
                <h3>@grouping.Key Standings</h3>
                @Html.Partial("Teams", grouping)

                if (ViewBag.HasEditAccess) {
                <em>@Html.ActionLink("Add Team", "Create", "Teams", new {tournamentSlug = ViewBag.TournamentSlug, group = grouping.Key}, null)</em>
                }
        
            }
        </td>

        <td>
            @if (ViewBag.HasEditAccess) {
                <em>@Html.ActionLink("Add Round", "Create", "Rounds", new {tournamentSlug = ViewBag.TournamentSlug}, null)</em>
            }
            <h2>Games</h2>
            @foreach (var round in Model.Rounds) {
                <h3>@round.Name</h3>
                
                @Html.Partial("Games", round.Games)
                if (ViewBag.HasEditAccess) {
                     <em>@Html.ActionLink("Add Game", "Create", "Games", new {id = round.Id, tournamentSlug = ViewBag.TournamentSlug}, null)</em>
                 }
            }
            
        </td>
    </tr>
</table>