TournamentMaker.Web/Models/Data/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace TournamentReport.Models
{
    public class Game
    {
        public int Id { get; set; }

        public ICollection<Team> Teams { get; set; }

        public Team HomeTeam
        {
            get
            {
                if (Teams == null)
                {
                    return null;
                }
                if (HomeTeamId == null)
                {
                    return Teams.FirstOrDefault();
                }
                return Teams.FirstOrDefault(t => t.Id == HomeTeamId.Value);
            }
        }

        public Team AwayTeam
        {
            get
            {
                if (Teams == null)
                {
                    return null;
                }
                if (AwayTeamId == null)
                {
                    return Teams.LastOrDefault();
                }
                return Teams.LastOrDefault(t => t.Id == AwayTeamId.Value);
            }
        }

        public void AddTeams(Team homeTeam, Team awayTeam)
        {
            if (Teams == null) return;
            Teams.Clear();
            Teams.Add(homeTeam);
            HomeTeamId = homeTeam.Id;
            Teams.Add(awayTeam);
            AwayTeamId = awayTeam.Id;
        }

        public int? HomeTeamId { get; set; }

        public int? AwayTeamId { get; set; }

        [Display(Name = "Home Team Score")]
        [Range(0, int.MaxValue, ErrorMessage = "Not sure how you score negative goals.")]
        public int? HomeTeamScore { get; set; }

        [Display(Name = "Away Team Score")]
        [Range(0, int.MaxValue, ErrorMessage = "Not sure how you score negative goals.")]

        public int? AwayTeamScore { get; set; }

        public Round Round { get; set; }

        public int RoundId { get; set; }

        public DateTime? GameTime { get; set; }

        public int? FieldId { get; set; }

        public Field Field { get; set; }

        public bool InGame(Team team)
        {
            return team.Id == HomeTeam.Id || team.Id == AwayTeam.Id;
        }
    }
}

TournamentMaker.Web/Models/Data/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace TournamentReport.Models {
    public class Team {
        private bool _standingsCalculated;
        public int Id { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        public string Group { get; set; }
        public Tournament Tournament { get; set; }

        public string Name { get; set; }
        public int Wins { get; private set; }
        public int Losses { get; private set; }
        public int Ties { get; private set; }

        public int GoalsScored { get; private set; }
        public int GoalsAgainst { get; private set; }

        public int GamesPlayed {
            get {
                if (Games == null) {
                    return 0;
                }
                return Games.Count(g => g.HomeTeamScore != null && g.InGame(this));
            }
        }
        public int Points {
            get {
                CalculateWinsLosses();
                return Wins * 3 + Ties;
            }
        }

        private void CalculateWinsLosses() {
            if (Games == null) {
                return;
            }
            if (!_standingsCalculated) {
                Wins = 0;
                Losses = 0;
                Ties = 0;
                GoalsScored = 0;
                GoalsAgainst = 0;

                Func<Game, GameResult> gameResultDeterminator = game => {
                    if (game.HomeTeamScore == null) {
                        return null;
                    }
                    if (game.HomeTeam != null && game.HomeTeam.Id == Id)
                    {
                        return new GameResult(game.HomeTeamScore.Value, game.AwayTeamScore.GetValueOrDefault());
                    }
                    if (game.AwayTeam != null && game.AwayTeam.Id == Id)
                    {
                        return new GameResult(game.AwayTeamScore.GetValueOrDefault(), game.HomeTeamScore.Value);
                    }
                    return null;
                };

                foreach (var game in Games) {
                    var gameResult = gameResultDeterminator(game);

                    if (gameResult != null) {
                        if (gameResult.ThisTeamScore > gameResult.OtherTeamScore) {
                            Wins++;
                        }
                        if (gameResult.ThisTeamScore < gameResult.OtherTeamScore) {
                            Losses++;
                        }
                        if (gameResult.ThisTeamScore == gameResult.OtherTeamScore) {
                            Ties++;
                        }
                        GoalsScored += gameResult.ThisTeamScore;
                        GoalsAgainst += gameResult.OtherTeamScore;
                    }
                }
            }
            _standingsCalculated = true;
        }
    }
}

TournamentMaker.Web/Controllers/GamesController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using TournamentReport.Models;

namespace TournamentReport.Controllers
{
    public class GamesController : Controller
    {
        readonly TournamentContext db = new TournamentContext();

        public ActionResult Create(string tournamentSlug, int id)
        {
            ViewBag.RoundId = new SelectList(db.Rounds, "Id", "Name", id);
            var teams = db.Teams.Where(t => t.Tournament.Slug == tournamentSlug);
            ViewBag.HomeTeamId = new SelectList(teams, "Id", "Name");
            ViewBag.AwayTeamId = new SelectList(teams, "Id", "Name");

            var fields = db.Fields.ToList();
            ViewBag.FieldId = new SelectList(fields, "Id", "Name");

            var model = new GameCreateModel
            {
                RoundId = id
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(GameCreateModel gameModel, string tournamentSlug)
        {
            if (gameModel.HomeTeamId == gameModel.AwayTeamId)
            {
                ModelState.AddModelError("AwayTeamId", "A team cannot play itself");
            }
            if (ModelState.IsValid)
            {
                var game = new Game
                {
                    RoundId = gameModel.RoundId.Value,
                    GameTime = gameModel.GameTime
                };
                db.Games.Add(game);
                db.SaveChanges();

                var model = new GameEditModel
                {
                    Id = game.Id,
                    HomeTeamId = gameModel.HomeTeamId,
                    AwayTeamId = gameModel.AwayTeamId,
                    GameTime = gameModel.GameTime,
                    FieldId = gameModel.FieldId
                };
                return Edit(model, tournamentSlug);
            }

            var teams = db.Teams.Where(t => t.Tournament.Slug == tournamentSlug);
            ViewBag.HomeTeamId = new SelectList(teams, "Id", "Name");
            ViewBag.AwayTeamId = new SelectList(teams, "Id", "Name");

            ViewBag.RoundId = new SelectList(db.Rounds, "Id", "Name", gameModel.RoundId);
            return View(gameModel);
        }

        public ActionResult ReportScores(int id, string tournamentSlug)
        {
            var game = db.Games.Include(g => g.Teams).FirstOrDefault(g => g.Id == id);
            return View(game);
        }

        [HttpPost]
        public ActionResult ReportScores(Game game, string tournamentSlug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Standings", "Home", new {tournamentSlug});
            }

            return View(game);
        }

        public ActionResult Edit(int id, string tournamentSlug)
        {
            var game = db.Games.Include(g => g.Teams).FirstOrDefault(g => g.Id == id);
            if (game == null) return HttpNotFound();

            var model = new GameEditModel
            {
                Id = game.Id
            };

            if (game.HomeTeam != null)
            {
                model.HomeTeamId = game.HomeTeam.Id;
            }
            if (game.AwayTeam != null)
            {
                model.AwayTeamId = game.AwayTeam.Id;
            }
            model.GameTime = game.GameTime;

            var teams = db.Teams.Where(t => t.Tournament.Slug == tournamentSlug);
            ViewBag.HomeTeamId = new SelectList(teams, "Id", "Name", model.HomeTeamId);
            ViewBag.AwayTeamId = new SelectList(teams, "Id", "Name", model.AwayTeamId);

            var fields = db.Fields.ToList();
            ViewBag.FieldId = new SelectList(fields, "Id", "Name", model.FieldId);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(GameEditModel game, string tournamentSlug)
        {
            if (game.HomeTeamId == game.AwayTeamId)
            {
                ModelState.AddModelError("AwayTeamId", "A team cannot play itself");
            }

            if (ModelState.IsValid)
            {
                var dbGame = db.Games.Include(g => g.Teams).FirstOrDefault(g => g.Id == game.Id);
                if (dbGame == null) return HttpNotFound();

                dbGame.AddTeams(db.Teams.Find(game.HomeTeamId), db.Teams.Find(game.AwayTeamId));
                dbGame.GameTime = game.GameTime;
                dbGame.FieldId = game.FieldId;
                db.SaveChanges();
                return RedirectToAction("Standings", "Home", new {tournamentSlug});
            }
            var teams = db.Teams.Where(t => t.Tournament.Slug == tournamentSlug);
            ViewBag.HomeTeamId = new SelectList(teams, "Id", "Name", game.HomeTeamId);
            ViewBag.AwayTeamId = new SelectList(teams, "Id", "Name", game.AwayTeamId);

            return View(game);
        }


        public ActionResult Delete(int id)
        {
            var game = db.Games.Find(id);
            return View(game);
        }

        //
        // POST: /Games/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string tournamentSlug)
        {
            var game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Standings", "Home", new {tournamentSlug});
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        [Authorize(Roles = "Administrators")]
        public ActionResult ResetScores(string tournamentSlug)
        {
            return View();
        }

        [Authorize(Roles = "Administrators")]
        [HttpPost]
        public ActionResult ResetScores(string tournamentSlug, string submit)
        {
            var games = (from team in db.Teams.Include(t => t.Games).Include(t => t.Tournament)
                where team.Tournament.Slug == tournamentSlug
                select team).SelectMany(t => t.Games).ToList();

            foreach (var game in games)
            {
                game.HomeTeamScore = null;
                game.AwayTeamScore = null;
            }
            db.SaveChanges();

            return RedirectToAction("Standings", "Home", new {tournamentSlug});
        }
    }
}

TournamentMaker.Web/Controllers/TeamsController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using TournamentReport.Models;

namespace TournamentReport.Controllers
{
    public class TeamsController : Controller
    {
        readonly TournamentContext db = new TournamentContext();

        public ActionResult Create(string group, string tournamentSlug)
        {
            ViewBag.Group = group;
            ViewBag.TournamentSlug = tournamentSlug;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Team team, string tournamentSlug)
        {
            if (ModelState.IsValid)
            {
                var tournament = db.Tournaments.First(t => t.Slug == tournamentSlug);
                team.Tournament = tournament;
                db.Teams.Add(team);
                db.SaveChanges();
                return RedirectToAction("Standings", "Home", new {tournamentSlug});
            }

            return View(team);
        }

        public ActionResult Edit(int id, string tournamentSlug)
        {
            var team = db.Teams.Include(t => t.Tournament).FirstOrDefault(t => t.Id == id);
            return View(team);
        }

        [HttpPost]
        public ActionResult Edit(Team team, string tournamentSlug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(team).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Standings", "Home", new {id = tournamentSlug});
            }
            return View(team);
        }

        public ActionResult Delete(int id)
        {
            var team = db.Teams.Include(t => t.Tournament).FirstOrDefault(t => t.Id == id);
            return View(team);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var team = db.Teams.Include(t => t.Tournament).FirstOrDefault(t => t.Id == id);
            if (team == null) return HttpNotFound();
            string tournamentSlug = team.Tournament.Slug;
            db.Teams.Remove(team);
            db.SaveChanges();
            return RedirectToAction("Standings", "Home", new { id = tournamentSlug });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TournamentMaker.Web/Views/Shared/Games.cshtml
@using System.Globalization
@model IEnumerable<Game>
           
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Field</th>
        <th>Home Team</th>
        <th>Score</th>
        <th>Away Team</th>
        <th>Score</th>
        @if (ViewBag.HasEditAccess) {
        <th></th>
        }
    </tr>

@foreach (var game in Model.OrderBy(t => t.Id)) {
    if (game.Teams == null || !game.Teams.Any()) {
        <tr>
            <td colspan="4">
            <em>TBD</em>
            </td>
            @if (ViewBag.HasEditAccess) {
                <td class="actions">
                    <a href="@Url.Action("Edit", "Games", new { id = game.Id, tournamentSlug = ViewBag.TournamentSlug })"><img src="/assets/images/editIcon.png" width="11" height="11" />Teams</a><br />
                </td>
            }
        </tr>
    }
    else {
    <tr>
        <td>
            @String.Format("{0:D}", game.GameTime)
        </td>
        <td>
            @String.Format("{0:t}", game.GameTime)
        </td>
        <td>
            @if (game.Field != null)
            {
                @Html.RouteLink(game.Field.Name, "Default", new {Controller = "Fields", Action = "Details", Id = game.FieldId})
            }
        </td>
        <td>
            @Html.DisplayFor(m => game.HomeTeam.Name)
        </td>
        <td>
            @Html.DisplayFor(m => game.HomeTeamScore)
        </td>
        <td>
            @Html.DisplayFor(m => game.AwayTeam.Name)
        </td>
        <td>
            @Html.DisplayFor(m => game.AwayTeamScore)
        </td>
        @if (ViewBag.HasEditAccess) {
            <td class="actions">
                <nobr><a href="@Url.Action("ReportScores", "Games", new { id = game.Id, tournamentSlug = ViewBag.TournamentSlug })"><img src="/assets/images/greenArrow.png" width="11" height="11" />Score</a></nobr><br />
                <nobr><a href="@Url.Action("Edit", "Games", new { id = game.Id, tournamentSlug = ViewBag.TournamentSlug })"><img src="/assets/images/editIcon.png" width="11" height="11" />Edit</a></nobr><br />
                <nobr><a href="@Url.Action("Delete", "Games", new { id = game.Id, tournamentSlug = ViewBag.TournamentSlug })"><img src="/assets/images/trash.png" width="11" height="11" />Delete</a></nobr>
            </td>
        }
    </tr>
    }
}
</table>

TournamentMaker.Web/Views/Shared/Teams.cshtml
@model IEnumerable<Team>

<table>
    <tr>
        <th>Name</th>
        <th>Games Played</th>
        <th>Wins</th>
        <th>Losses</th>
        <th>Ties</th>
        <th>Goals For</th>
        <th>Goals Against</th>
        <th>Points</th>
        @if (ViewBag.HasEditAccess) {
        <th></th>
        }
    </tr>

@foreach (var team in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelteam => team.Name)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.GamesPlayed)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.Wins)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.Losses)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.Ties)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.GoalsScored)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.GoalsAgainst)
        </td>
        <td>
            @Html.DisplayFor(modelteam => team.Points)
        </td>
        @if (ViewBag.HasEditAccess) {
            <td class="actions">
                <nobr>
                    <a href="@Url.Action("Edit", "Teams", new {id = team.Id, tournamentSlug = team.Tournament.Slug})"><img src="/assets/images/editIcon.png" width="11" height="11" />Edit</a> 
                    <a href="@Url.Action("Delete", "Teams", new { id = team.Id, tournamentSlug = team.Tournament.Slug})"><img src="/assets/images/trash.png" width="11" height="11" />Delete</a>
                </nobr>
            </td>
        }
    </tr>
}
</table>

TournamentMaker.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="/assets/css/Site.css" rel="stylesheet" type="text/css" />
    <script src="/assets/js/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.validate.min.js" type="text/javascript"></script>
    <script src="/assets/js/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="/assets/js/modernizr-2.7.2.js" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <nav>
                <div id="logindisplay">
                    @Html.Partial("_LogOnPartial")
                </div>
                <ul id="menu">
                    <li><a href="/">Tournaments</a></li>
                    <li><a href="/tournaments/2015-timbers-com-cup-mens">Mens</a></li>
                    <li><a href="/tournaments/2015-timbers-com-cup-coed">Coed</a></li>
                </ul>
            </nav>
        </header>
        <section id="main">
            <div id="main-logo"></div>
            @RenderBody()
        </section>
        <footer>
            <p>Hosting graciously provided by <img src="/assets/images/newtek-logo.png" height="50" valign="top" /></p>
        </footer>
    </div>
</body>
</html>

TournamentMaker.Web/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") | @Html.ActionLink("Change Password", "ChangePassword", "Account")</text>
    if (ViewBag.HasEditAccess) {
        <span>| <a href="/dbadmin">Database Admin</a></span>
        <span>| @Html.RouteLink("Fields", "Default", new { Controller="Fields", Action="Index" })</span>
    }
    <span>]</span>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}